language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t matsit56/multi_container_client_test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true matsit56/multi_container_client_test npm test

after_success:
  -docker build -t matsit56/multi_container_client ./client
  -docker build -t matsit56/multi_container_nginx ./nginx
  -docker build -t matsit56/multi_container_server ./server
  -docker build -t matsit56/multi_container_worker ./worker
  #Log in to docker CLI
  -echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub
  - docker push matsit56/multi_container_client
  - docker push matsit56/multi_container_nginx
  - docker push matsit56/multi_container_server
  - docker push matsit56/multi_container_worker


deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-443965624465"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"